version: "3.8"

services:
  client:
    image: shippingportsclient
    container_name: shippingportsclient_1
    ports:
      - "8080:8080"
    volumes:
      - ${BIND_PATH}:/dropbox
    environment:
      - LOAD_SHIPPING_PORTS_JSON_FILENAME=${JSON_FILENAME}
      - SERVE_CLIENT_AT_ADDRESS=:8080
      - SERVER_ADDRESS=shippingportsserver_1:50051
      - LOAD_SHIPPING_PORTS_PUTTERS=4

  server:
    image: shippingportsserver
    container_name: shippingportsserver_1
    environment:
      - SERVE_AT_ADDRESS=:50051
