// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.14.0
// source: shippingportsprotocol/shippingports.proto

package shippingportsprotocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShippingPortsServerClient is the client API for ShippingPortsServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShippingPortsServerClient interface {
	// Sends a ShippingPort to be saved
	Put(ctx context.Context, in *ShippingPort, opts ...grpc.CallOption) (*Ok, error)
	// Request a ShippingPort by its id
	Get(ctx context.Context, in *ShippingPortId, opts ...grpc.CallOption) (*ShippingPort, error)
}

type shippingPortsServerClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingPortsServerClient(cc grpc.ClientConnInterface) ShippingPortsServerClient {
	return &shippingPortsServerClient{cc}
}

func (c *shippingPortsServerClient) Put(ctx context.Context, in *ShippingPort, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := c.cc.Invoke(ctx, "/shippingportsprotocol.ShippingPortsServer/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingPortsServerClient) Get(ctx context.Context, in *ShippingPortId, opts ...grpc.CallOption) (*ShippingPort, error) {
	out := new(ShippingPort)
	err := c.cc.Invoke(ctx, "/shippingportsprotocol.ShippingPortsServer/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingPortsServerServer is the server API for ShippingPortsServer service.
// All implementations must embed UnimplementedShippingPortsServerServer
// for forward compatibility
type ShippingPortsServerServer interface {
	// Sends a ShippingPort to be saved
	Put(context.Context, *ShippingPort) (*Ok, error)
	// Request a ShippingPort by its id
	Get(context.Context, *ShippingPortId) (*ShippingPort, error)
	mustEmbedUnimplementedShippingPortsServerServer()
}

// UnimplementedShippingPortsServerServer must be embedded to have forward compatible implementations.
type UnimplementedShippingPortsServerServer struct {
}

func (UnimplementedShippingPortsServerServer) Put(context.Context, *ShippingPort) (*Ok, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedShippingPortsServerServer) Get(context.Context, *ShippingPortId) (*ShippingPort, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedShippingPortsServerServer) mustEmbedUnimplementedShippingPortsServerServer() {}

// UnsafeShippingPortsServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingPortsServerServer will
// result in compilation errors.
type UnsafeShippingPortsServerServer interface {
	mustEmbedUnimplementedShippingPortsServerServer()
}

func RegisterShippingPortsServerServer(s grpc.ServiceRegistrar, srv ShippingPortsServerServer) {
	s.RegisterService(&ShippingPortsServer_ServiceDesc, srv)
}

func _ShippingPortsServer_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShippingPort)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingPortsServerServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shippingportsprotocol.ShippingPortsServer/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingPortsServerServer).Put(ctx, req.(*ShippingPort))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingPortsServer_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShippingPortId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingPortsServerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shippingportsprotocol.ShippingPortsServer/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingPortsServerServer).Get(ctx, req.(*ShippingPortId))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingPortsServer_ServiceDesc is the grpc.ServiceDesc for ShippingPortsServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingPortsServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shippingportsprotocol.ShippingPortsServer",
	HandlerType: (*ShippingPortsServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _ShippingPortsServer_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ShippingPortsServer_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shippingportsprotocol/shippingports.proto",
}
